# Declaring Tensors

### © Jubeen Shah 2018

Hey there! Welcome to `J.S Codes` jupyter notebooks for TensorFlow!
<br>


In `TensorFlow`, the primary data structures that are used are `Tensors`, which are used to operate on the __Computational Graphs__. We can define these tensors in two ways:
 - *Variables*
 - Feed them in using *Placeholders*
<br>

We already saw the use of placeholders with `tf.placeholder()` in the previous notebooks. But there are other ways of declaring some *standard forms* of Tensors. In this notebook we will see how to do that! 

In [51]:
import tensorflow as tf

## 1. Fixed Tensors
 - To create a Zero filled tensor, use the following.

In [52]:
zero_tensor = tf.zeros([5,5])
with tf.Session() as sess:
    zero = sess.run(zero_tensor)
    print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [53]:
??tf.zeros() #Run this cell to know more about this function

 - To create a one filled tensor, use the following

In [54]:
ones_tensor = tf.ones([5,5])
sess = tf.Session()
one = sess.run(ones_tensor)
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [55]:
??tf.ones() #Run this cell to know more about this function

 - To create a constant filled tensor, use the following

In [56]:
const_tensor = tf.fill([7,7], 42)
const = sess.run(const_tensor)
print(const)

[[42 42 42 42 42 42 42]
 [42 42 42 42 42 42 42]
 [42 42 42 42 42 42 42]
 [42 42 42 42 42 42 42]
 [42 42 42 42 42 42 42]
 [42 42 42 42 42 42 42]
 [42 42 42 42 42 42 42]]


In [57]:
?? tf.fill() #Run this cell to know more about this function

## 2. Tensors of similar shape
 - We can also initialise variables based on the shape of other tensors, as follows

In [58]:
zeros_similar = tf.zeros_like(const_tensor)
zeros_sim = sess.run(zeros_similar)
print(zeros_sim)
print()
ones_similar = tf.ones_like(const_tensor)
ones_sim = sess.run(ones_similar)
print(ones_sim)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


## 3. Sequence Tensors
 - TensorFlow allows us to define tensors of specified shape using `tf.linspace()` for creating values at __regular__ intervals in a *linear space*

In [65]:
# Allows to create a tensor that contains values at regular intervals, specified by num = (Value) 
start = 0.0 #Enter a float
stop = 1.0  #Enter a float
num = 30    #Enter a int
linear_tensor = tf.linspace(start=start, stop=stop, num = num) 
print_linear_tensor = sess.run(linear_tensor)
print(print_linear_tensor)

[0.         0.03448276 0.06896552 0.10344827 0.13793103 0.1724138
 0.20689654 0.2413793  0.27586207 0.31034482 0.3448276  0.37931034
 0.4137931  0.44827586 0.4827586  0.51724136 0.55172414 0.5862069
 0.62068963 0.6551724  0.6896552  0.7241379  0.7586207  0.79310346
 0.8275862  0.86206895 0.8965517  0.9310345  0.9655172  1.        ]


In [66]:
??tf.linspace #Run this cell to know more about this function

 - To create an integer sequence, use the following

In [67]:
start = 6.0
limit = 150
delta = 2.5
integer_sequence_tensor = tf.range(start = start , limit = limit, delta = delta) 
print_integer_sequence_tensor = sess.run(integer_sequence_tensor)
print(print_integer_sequence_tensor)

[  6.    8.5  11.   13.5  16.   18.5  21.   23.5  26.   28.5  31.   33.5
  36.   38.5  41.   43.5  46.   48.5  51.   53.5  56.   58.5  61.   63.5
  66.   68.5  71.   73.5  76.   78.5  81.   83.5  86.   88.5  91.   93.5
  96.   98.5 101.  103.5 106.  108.5 111.  113.5 116.  118.5 121.  123.5
 126.  128.5 131.  133.5 136.  138.5 141.  143.5 146.  148.5]


In [68]:
start = 6
limit = 20
delta = 4
integer_sequence_tensor = tf.range(start = start , limit = limit, delta = delta) 
print_integer_sequence_tensor = sess.run(integer_sequence_tensor)
print(print_integer_sequence_tensor)

[ 6 10 14 18]


In [69]:
??tf.range

## 4. Random Tensors
 - Random Uniform Distribution

In [82]:
# Outputs random values from a uniform distribution.
row = 1
col = 5
minval = 0
maxval = 4
rand_uniform_distribution = tf.random_uniform([row,col], minval=minval, maxval=maxval)
print_rand_uniform_distribution = sess.run(rand_uniform_distribution)
print(print_rand_uniform_distribution)

[[2.38061   1.6223726 3.6629162 3.7106738 3.6365976]]


In [81]:
??tf.random_uniform #Run this cell to know more about this function

 - Random Normal Distribution

In [87]:
# Outputs random values from a Normal distribution.
row = 1
col = 5
mean = 0.0
std_dev = 1.0

rand_norm_distribution = tf.random_normal([row,col], mean = mean, stddev= std_dev)
print_rand_norm_distribution = sess.run(rand_norm_distribution)
print(print_rand_norm_distribution)

[[ 0.8290883  -1.1310698  -0.81308913 -0.02191718  0.56976753]]


In [88]:
??tf.random_normal

In [89]:
# Outputs random values from a truncated normal distribution.
row = 1
col = 5
mean = 0.0
std_dev = 1.0

rand_norm_distribution = tf.truncated_normal([row,col], mean = mean, stddev= std_dev)
print_rand_norm_distribution = sess.run(rand_norm_distribution)
print(print_rand_norm_distribution)

[[ 0.8814421  -0.4408187  -1.1982943  -0.9001718   0.13855277]]


In [91]:
??tf.truncated_normal

### ¡Basta para ahora Amigos!

In the next notebook, we'll continue with placeholders and variables! 
##### ¡Hasta Pronto!
